import { Dimensions } from "react-native";

export const Country = [
  { label: 'Afghanistan', value: 'Afghanistan' },
  { label: 'Albania', value: 'Albania' },
  { label: 'Algeria', value: 'Algeria' },
  { label: 'Andorra', value: 'Andorra' },
  { label: 'Angola', value: 'Angola' },
  { label: 'Antigua and Barbuda', value: 'Antigua and Barbuda' },
  { label: 'Argentina', value: 'Argentina' },
  { label: 'Armenia', value: 'Armenia' },
  { label: 'Australia', value: 'Australia' },
  { label: 'Austria', value: 'Austria' },
  { label: 'Azerbaijan', value: 'Azerbaijan' },
  { label: 'Bahamas', value: 'Bahamas' },
  { label: 'Bahrain', value: 'Bahrain' },
  { label: 'Bangladesh', value: 'Bangladesh' },
  { label: 'Barbados', value: 'Barbados' },
  { label: 'Belarus', value: 'Belarus' },
  { label: 'Belgium', value: 'Belgium' },
  { label: 'Belize', value: 'Belize' },
  { label: 'Benin', value: 'Benin' },
  { label: 'Bhutan', value: 'Bhutan' },
  { label: 'Bolivia', value: 'Bolivia' },
  { label: 'Bosnia and Herzegovina', value: 'Bosnia and Herzegovina' },
  { label: 'Botswana', value: 'Botswana' },
  { label: 'Brazil', value: 'Brazil' },
  { label: 'Brunei', value: 'Brunei' },
  { label: 'Bulgaria', value: 'Bulgaria' },
  { label: 'Burkina Faso', value: 'Burkina Faso' },
  { label: 'Burundi', value: 'Burundi' },
  { label: 'Cabo Verde', value: 'Cabo Verde' },
  { label: 'Cambodia', value: 'Cambodia' },
  { label: 'Cameroon', value: 'Cameroon' },
  { label: 'Canada', value: 'Canada' },
  { label: 'Central African Republic', value: 'Central African Republic' },
  { label: 'Chad', value: 'Chad' },
  { label: 'Chile', value: 'Chile' },
  { label: 'China', value: 'China' },
  { label: 'Colombia', value: 'Colombia' },
  { label: 'Comoros', value: 'Comoros' },
  { label: 'Congo (Congo-Brazzaville)', value: 'Congo (Congo-Brazzaville)' },
  { label: 'Costa Rica', value: 'Costa Rica' },
  { label: 'Croatia', value: 'Croatia' },
  { label: 'Cuba', value: 'Cuba' },
  { label: 'Cyprus', value: 'Cyprus' },
  { label: 'Czechia (Czech Republic)', value: 'Czechia (Czech Republic)' },
  { label: 'Denmark', value: 'Denmark' },
  { label: 'Djibouti', value: 'Djibouti' },
  { label: 'Dominica', value: 'Dominica' },
  { label: 'Dominican Republic', value: 'Dominican Republic' },
  { label: 'Ecuador', value: 'Ecuador' },
  { label: 'Egypt', value: 'Egypt' },
  { label: 'El Salvador', value: 'El Salvador' },
  { label: 'Equatorial Guinea', value: 'Equatorial Guinea' },
  { label: 'Eritrea', value: 'Eritrea' },
  { label: 'Estonia', value: 'Estonia' },
  {
    label: 'Eswatini (fmr. "Swaziland")',
    value: 'Eswatini (fmr. "Swaziland")',
  },
  { label: 'Ethiopia', value: 'Ethiopia' },
  { label: 'Fiji', value: 'Fiji' },
  { label: 'Finland', value: 'Finland' },
  { label: 'France', value: 'France' },
  { label: 'Gabon', value: 'Gabon' },
  { label: 'Gambia', value: 'Gambia' },
  { label: 'Georgia', value: 'Georgia' },
  { label: 'Germany', value: 'Germany' },
  { label: 'Ghana', value: 'Ghana' },
  { label: 'Greece', value: 'Greece' },
  { label: 'Grenada', value: 'Grenada' },
  { label: 'Guatemala', value: 'Guatemala' },
  { label: 'Guinea', value: 'Guinea' },
  { label: 'Guinea-Bissau', value: 'Guinea-Bissau' },
  { label: 'Guyana', value: 'Guyana' },
  { label: 'Haiti', value: 'Haiti' },
  { label: 'Holy See', value: 'Holy See' },
  { label: 'Honduras', value: 'Honduras' },
  { label: 'Hungary', value: 'Hungary' },
  { label: 'Iceland', value: 'Iceland' },
  { label: 'India', value: 'India' },
  { label: 'Indonesia', value: 'Indonesia' },
  { label: 'Iran', value: 'Iran' },
  { label: 'Iraq', value: 'Iraq' },
  { label: 'Ireland', value: 'Ireland' },
  { label: 'Israel', value: 'Israel' },
  { label: 'Italy', value: 'Italy' },
  { label: 'Jamaica', value: 'Jamaica' },
  { label: 'Japan', value: 'Japan' },
  { label: 'Jordan', value: 'Jordan' },
  { label: 'Kazakhstan', value: 'Kazakhstan' },
  { label: 'Kenya', value: 'Kenya' },
  { label: 'Kiribati', value: 'Kiribati' },
  { label: 'Korea, North', value: 'Korea, North' },
  { label: 'Korea, South', value: 'Korea, South' },
  { label: 'Kosovo', value: 'Kosovo' },
  { label: 'Kuwait', value: 'Kuwait' },
  { label: 'Kyrgyzstan', value: 'Kyrgyzstan' },
  { label: 'Laos', value: 'Laos' },
  { label: 'Latvia', value: 'Latvia' },
  { label: 'Lebanon', value: 'Lebanon' },
  { label: 'Lesotho', value: 'Lesotho' },
  { label: 'Liberia', value: 'Liberia' },
  { label: 'Libya', value: 'Libya' },
  { label: 'Liechtenstein', value: 'Liechtenstein' },
  { label: 'Lithuania', value: 'Lithuania' },
  { label: 'Luxembourg', value: 'Luxembourg' },
  { label: 'Madagascar', value: 'Madagascar' },
  { label: 'Malawi', value: 'Malawi' },
  { label: 'Malaysia', value: 'Malaysia' },
  { label: 'Maldives', value: 'Maldives' },
  { label: 'Mali', value: 'Mali' },
  { label: 'Malta', value: 'Malta' },
  { label: 'Marshall Islands', value: 'Marshall Islands' },
  { label: 'Mauritania', value: 'Mauritania' },
  { label: 'Mauritius', value: 'Mauritius' },
  { label: 'Mexico', value: 'Mexico' },
  { label: 'Micronesia', value: 'Micronesia' },
  { label: 'Moldova', value: 'Moldova' },
  { label: 'Monaco', value: 'Monaco' },
  { label: 'Mongolia', value: 'Mongolia' },
  { label: 'Montenegro', value: 'Montenegro' },
  { label: 'Morocco', value: 'Morocco' },
  { label: 'Mozambique', value: 'Mozambique' },
  { label: 'Myanmar (formerly Burma)', value: 'Myanmar (formerly Burma)' },
  { label: 'Namibia', value: 'Namibia' },
  { label: 'Nauru', value: 'Nauru' },
  { label: 'Nepal', value: 'Nepal' },
  { label: 'Netherlands', value: 'Netherlands' },
  { label: 'New Zealand', value: 'New Zealand' },
  { label: 'Nicaragua', value: 'Nicaragua' },
  { label: 'Niger', value: 'Niger' },
  { label: 'Nigeria', value: 'Nigeria' },
  { label: 'North Macedonia', value: 'North Macedonia' },
  { label: 'Norway', value: 'Norway' },
  { label: 'Oman', value: 'Oman' },
  { label: 'Pakistan', value: 'Pakistan' },
  { label: 'Palau', value: 'Palau' },
  { label: 'Palestine State', value: 'Palestine State' },
  { label: 'Panama', value: 'Panama' },
  { label: 'Papua New Guinea', value: 'Papua New Guinea' },
  { label: 'Paraguay', value: 'Paraguay' },
  { label: 'Peru', value: 'Peru' },
  { label: 'Philippines', value: 'Philippines' },
  { label: 'Poland', value: 'Poland' },
  { label: 'Portugal', value: 'Portugal' },
  { label: 'Qatar', value: 'Qatar' },
  { label: 'Romania', value: 'Romania' },
  { label: 'Russia', value: 'Russia' },
  { label: 'Rwanda', value: 'Rwanda' },
  { label: 'Saint Kitts and Nevis', value: 'Saint Kitts and Nevis' },
  { label: 'Saint Lucia', value: 'Saint Lucia' },
  {
    label: 'Saint Vincent and the Grenadines',
    value: 'Saint Vincent and the Grenadines',
  },
  { label: 'Samoa', value: 'Samoa' },
  { label: 'San Marino', value: 'San Marino' },
  { label: 'Sao Tome and Principe', value: 'Sao Tome and Principe' },
  { label: 'Saudi Arabia', value: 'Saudi Arabia' },
  { label: 'Senegal', value: 'Senegal' },
  { label: 'Serbia', value: 'Serbia' },
  { label: 'Seychelles', value: 'Seychelles' },
  { label: 'Sierra Leone', value: 'Sierra Leone' },
  { label: 'Singapore', value: 'Singapore' },
  { label: 'Slovakia', value: 'Slovakia' },
  { label: 'Slovenia', value: 'Slovenia' },
  { label: 'Solomon Islands', value: 'Solomon Islands' },
  { label: 'Somalia', value: 'Somalia' },
  { label: 'South Africa', value: 'South Africa' },
  { label: 'South Sudan', value: 'South Sudan' },
  { label: 'Spain', value: 'Spain' },
  { label: 'Sri Lanka', value: 'Sri Lanka' },
  { label: 'Sudan', value: 'Sudan' },
  { label: 'Suriname', value: 'Suriname' },
  { label: 'Sweden', value: 'Sweden' },
  { label: 'Switzerland', value: 'Switzerland' },
  { label: 'Syria', value: 'Syria' },
  { label: 'Taiwan', value: 'Taiwan' },
  { label: 'Tajikistan', value: 'Tajikistan' },
  { label: 'Tanzania', value: 'Tanzania' },
  { label: 'Thailand', value: 'Thailand' },
  { label: 'Timor-Leste', value: 'Timor-Leste' },
  { label: 'Togo', value: 'Togo' },
  { label: 'Tonga', value: 'Tonga' },
  { label: 'Trinidad and Tobago', value: 'Trinidad and Tobago' },
  { label: 'Tunisia', value: 'Tunisia' },
  { label: 'Turkey', value: 'Turkey' },
  { label: 'Turkmenistan', value: 'Turkmenistan' },
  { label: 'Tuvalu', value: 'Tuvalu' },
  { label: 'Uganda', value: 'Uganda' },
  { label: 'Ukraine', value: 'Ukraine' },
  { label: 'United Arab Emirates', value: 'United Arab Emirates' },
  { label: 'United Kingdom', value: 'United Kingdom' },
  { label: 'United States', value: 'United States' },
  { label: 'Uruguay', value: 'Uruguay' },
  { label: 'Uzbekistan', value: 'Uzbekistan' },
  { label: 'Vanuatu', value: 'Vanuatu' },
  { label: 'Venezuela', value: 'Venezuela' },
  { label: 'Vietnam', value: 'Vietnam' },
  { label: 'Yemen', value: 'Yemen' },
  { label: 'Zambia', value: 'Zambia' },
  { label: 'Zimbabwe', value: 'Zimbabwe' },
];
export const Provinces = [
  { label: 'Punjab', value: 'Punjab' },
  { label: 'Sindh', value: 'Sindh' },
  { label: 'Khyber Pakhtunkhwa', value: 'Khyber Pakhtunkhwa' },
  { label: 'Balochistan', value: 'Balochistan' },
  { label: 'Gilgit-Baltistan', value: 'Gilgit-Baltistan' },
  { label: 'Azad Kashmir', value: 'Azad Kashmir' },
  {
    label: 'Islamabad Capital Territory',
    value: 'Islamabad Capital Territory',
  },
];
export const Cities = [
  { label: 'Karachi', value: 'Karachi' },
  { label: 'Lahore', value: 'Lahore' },
  { label: 'Islamabad', value: 'Islamabad' },
  { label: 'Rawalpindi', value: 'Rawalpindi' },
  { label: 'Faisalabad', value: 'Faisalabad' },
  { label: 'Multan', value: 'Multan' },
  { label: 'Peshawar', value: 'Peshawar' },
  { label: 'Quetta', value: 'Quetta' },
  { label: 'Hyderabad', value: 'Hyderabad' },
  { label: 'Gujranwala', value: 'Gujranwala' },
];
export const MartialStatus = [
  { label: 'Single', value: 'Single' },
  { label: 'Married', value: 'Married' },
  { label: 'Divorced', value: 'Divorced' },
  { label: 'Widowed', value: 'Widowed' },
  { label: 'Separated', value: 'Separated' },
];
export const TotalChildren = [
  { label: '0', value: '0' },
  { label: '1', value: '1' },
  { label: '2', value: '2' },
  { label: '3', value: '3' },
  { label: '4', value: '4' },
  { label: '5', value: '5' },
  { label: '6', value: '6' },
  { label: '7', value: '7' },
];
export const Education = [
  { label: 'Matric', value: 'Matric' },
  { label: 'Intermediate', value: 'Intermediate' },
  { label: 'Bachelor', value: 'Bachelor' },
  { label: 'Master', value: 'Master' },
  { label: 'PhD', value: 'PhD' },
  { label: 'Diploma', value: 'Diploma' },
  { label: 'Certification', value: 'Certification' },
  { label: 'Vocational', value: 'Vocational' },
  { label: 'Primary', value: 'Primary' },
  { label: 'Secondary', value: 'Secondary' },
];
export const EmpolementType = [
  { label: 'Employed', value: 'Employed' },
  { label: 'Unemployed', value: 'Unemployed' },
  { label: 'Self-employed', value: 'Self-employed' },
  { label: 'Retired', value: 'Retired' },
  { label: 'Student', value: 'Student' },
  { label: 'Homemaker', value: 'Homemaker' },
  { label: 'Freelancer', value: 'Freelancer' },
  { label: 'Contractor', value: 'Contractor' },
  { label: 'Part-time', value: 'Part-time' },
  { label: 'Volunteer', value: 'Volunteer' },
];
export const Salary = [
  { label: 'Less than ₨500,000', value: 'Less than ₨500,000' },
  { label: '₨500,000 - ₨1,000,000', value: '₨500,000 - ₨1,000,000' },
  { label: '₨1,000,000 - ₨1,500,000', value: '₨1,000,000 - ₨1,500,000' },
  { label: '₨1,500,000 - ₨2,000,000', value: '₨1,500,000 - ₨2,000,000' },
  { label: '₨2,000,000 - ₨2,500,000', value: '₨2,000,000 - ₨2,500,000' },
  { label: '₨2,500,000 - ₨3,000,000', value: '₨2,500,000 - ₨3,000,000' },
  { label: '₨3,000,000 - ₨3,500,000', value: '₨3,000,000 - ₨3,500,000' },
  { label: '₨3,500,000 - ₨4,000,000', value: '₨3,500,000 - ₨4,000,000' },
  { label: '₨4,000,000 - ₨4,500,000', value: '₨4,000,000 - ₨4,500,000' },
  { label: 'More than ₨4,500,000', value: 'More than ₨4,500,000' },
];
export const Occupation = [
  { label: 'Engineer', value: 'Engineer' },
  { label: 'Doctor', value: 'Doctor' },
  { label: 'Teacher', value: 'Teacher' },
  { label: 'Accountant', value: 'Accountant' },
  { label: 'Lawyer', value: 'Lawyer' },
  { label: 'Software Developer', value: 'Software Developer' },
  { label: 'Artist', value: 'Artist' },
  { label: 'Salesperson', value: 'Salesperson' },
  { label: 'Nurse', value: 'Nurse' },
  { label: 'Marketing Manager', value: 'Marketing Manager' },
];
export const Designation = [
  { label: 'Manager', value: 'Manager' },
  { label: 'Supervisor', value: 'Supervisor' },
  { label: 'Director', value: 'Director' },
  { label: 'Coordinator', value: 'Coordinator' },
  { label: 'Executive', value: 'Executive' },
  { label: 'Analyst', value: 'Analyst' },
  { label: 'Specialist', value: 'Specialist' },
  { label: 'Officer', value: 'Officer' },
  { label: 'Consultant', value: 'Consultant' },
  { label: 'Administrator', value: 'Administrator' },
];
export const HeightInFeet = [
  { label: '3 ft', value: '3 ft' },
  { label: '4 ft', value: '4 ft' },
  { label: '5 ft', value: '5 ft' },
  { label: '6 ft', value: '6 ft' },
  { label: '7 ft', value: '7 ft' },
  { label: '8 ft', value: '8 ft' },
];
export const HeightInInch = [
  { label: '1 inch', value: '1 inch' },
  { label: '2 inch', value: '2 inch' },
  { label: '3 inch', value: '3 inch' },
  { label: '4 inch', value: '4 inch' },
  { label: '5 inch', value: '5 inch' },
  { label: '6 inch', value: '6 inch' },
  { label: '7 inch', value: '7 inch' },
  { label: '8 inch', value: '8 inch' },
  { label: '9 inch', value: '9 inch' },
  { label: '10 inch', value: '10 inch' },
  { label: '11 inch', value: '11 inch' },
  { label: '12 inch', value: '12 inch' },
];
export const Width = [
  { label: 'Slim', value: 'Slim' },
  { label: 'Average', value: 'Average' },
  { label: 'Athletic', value: 'Athletic' },
  { label: 'Broad', value: 'Broad' },
  { label: 'Heavyset', value: 'Heavyset' },
  { label: 'Petite', value: 'Petite' },
  { label: 'Curvy', value: 'Curvy' },
  { label: 'Voluptuous', value: 'Voluptuous' },
];
export const EatingHabits = [
  { label: 'Vegetarian', value: 'Vegetarian' },
  { label: 'Vegan', value: 'Vegan' },
  { label: 'Pescatarian', value: 'Pescatarian' },
  { label: 'Flexitarian', value: 'Flexitarian' },
  { label: 'Paleo', value: 'Paleo' },
  { label: 'Keto', value: 'Keto' },
  { label: 'Gluten-Free', value: 'Gluten-Free' },
  { label: 'Lactose-Free', value: 'Lactose-Free' },
  { label: 'Halal', value: 'Halal' },
  { label: 'Kosher', value: 'Kosher' },
];
export const BooleanArray = [
  { label: 'Yes', value: 'Yes' },
  { label: 'No', value: 'No' },
];
export const BodyType = [
  { label: 'Slim', value: 'Slim' },
  { label: 'Average', value: 'Average' },
  { label: 'Athletic', value: 'Athletic' },
  { label: 'Broad', value: 'Broad' },
  { label: 'Heavyset', value: 'Heavyset' },
  { label: 'Petite', value: 'Petite' },
  { label: 'Curvy', value: 'Curvy' },
  { label: 'Voluptuous', value: 'Voluptuous' },
];
export const SkinTone = [
  { label: 'Fair', value: 'Fair' },
  { label: 'Light', value: 'Light' },
  { label: 'Medium', value: 'Medium' },
  { label: 'Olive', value: 'Olive' },
  { label: 'Tan', value: 'Tan' },
  { label: 'Dark', value: 'Dark' },
  { label: 'Deep', value: 'Deep' },
  { label: 'Ebony', value: 'Ebony' },
];
export const Complexion = [
  { label: 'Fair', value: 'Fair' },
  { label: 'Medium', value: 'Medium' },
  { label: 'Olive', value: 'Olive' },
  { label: 'Dark', value: 'Dark' },
];
export const MotherTongue = [
  { label: 'Urdu', value: 'Urdu' },
  { label: 'Punjabi', value: 'Punjabi' },
  { label: 'Sindhi', value: 'Sindhi' },
  { label: 'Pashto', value: 'Pashto' },
  { label: 'Balochi', value: 'Balochi' },
  { label: 'Saraiki', value: 'Saraiki' },
  { label: 'Kashmiri', value: 'Kashmiri' },
  { label: 'Hindko', value: 'Hindko' },
  { label: 'Brahui', value: 'Brahui' },
  { label: 'Shina', value: 'Shina' },
  { label: 'Burushaski', value: 'Burushaski' },
  { label: 'Others', value: 'Others' },
];
export const Religion = [
  { label: 'Islam', value: 'Islam' },
  { label: 'Christianity', value: 'Christianity' },
  { label: 'Hinduism', value: 'Hinduism' },
  { label: 'Sikhism', value: 'Sikhism' },
  { label: 'Buddhism', value: 'Buddhism' },
  { label: 'Judaism', value: 'Judaism' },
  { label: 'Other', value: 'Other' },
];
export const Caste = [
  { label: 'Arain', value: 'Arain' },
  { label: 'Jutt', value: 'Jutt' },
  { label: 'Rajput', value: 'Rajput' },
  { label: 'Mughal', value: 'Mughal' },
  { label: 'Syed', value: 'Syed' },
  { label: 'Sheikh', value: 'Sheikh' },
  { label: 'Pathan', value: 'Pathan' },
  { label: 'Kashmiri', value: 'Kashmiri' },
  { label: 'Baloch', value: 'Baloch' },
  { label: 'Sindhi', value: 'Sindhi' },
];
export const dataArray = [
  {
    question: 'Name',
    value: 'userFirstName',
  },
  {
    question: 'Martial Status',
    value: "userGender",
  },
  {
    question: 'Mother Tongue',
    value: 'userTongue',
  },
  {
    question: 'Languages',
    value: 'userTongue',
  },
  {
    question: 'Total Children',
    value: 'userchildrens',
  },
  {
    question: 'Children Status',
    value: 'userstatusChildren',
  },
  {
    question: 'Height',
    value: 'userHeightInFeet',
  },
  {
    question: 'Weight',
    value: 'userWidth',
  },
  {
    question: 'Birthday',
    value: 'userDateofBirth',
  },
  {
    question: '',
    value: '',
  },
];
export const userDetailKeyValueMatch = [
  { label: 'Complexion', value: 'userSkinTone' },
  { label: 'Mother Tongue', value: 'userTongue' },
  { label: 'Religion', value: 'userReligion' },
  { label: 'Caste', value: 'userCaste' },
  { label: 'City', value: 'userCity' },
  { label: 'Country', value: 'userCountry' },

];
export const adminUser = {
  email: 'Easyrishta3@gmail.com',
  password: 'Pakistan@99'
}

export const height_screen = Dimensions.get('window').height;
export const getSize = size => size;

export const colors = {
  colorPrimary: '#980303',
  colorSecondary: '#0075FF',
  colorSecondaryOf: '#0057FF',

  lightBlueBack: '#1FAAFF',
  lightWhiteColor: '#E5E5E5',

  greylighColor: '#C4C4C4',
  greydarkColor: '#77818C',
  secondaryDarkColor: '#397CFF',
  secondaryMediumColor: '#68A5FF',
  secondaryLightColor: '#EBF2FF',
  mapTopBack: '#1678F9',

  extraDarkColor: '#0B141F',
  highDarkColor: '#414F60',
  mediumDarkColor: '#8FA0B4',
  lightDarkColor: '#AAB7C6',

  extraLightColor: '#F3F5F9',

  blackColor: '#000000',
  borderColors: '#0075FF26',
  whiteColor: '#ffffff',
  whiteDimColor: '#ffffff29',
  backColorOfGrey: '#F2F2F2',

  colorError: '#FF3737',
  yellowColor: '#FFD04E',
  greenColor: '#148352',
  clackHeadColor: '#2D2C2C',
  greySubHeadColor: '#8B8B8B',
  greenImg: '#03433D',
  grayBttNColor: '#66D8D8D8',
  updateBtnBackColor: '#D8D8D8',
  greyBtnTextColor: '#838383',
  bggreylightColor: '#F5F4F9',
  orangeColor: '#FF8C00',
  btnBackColor: '#00854A',
  redLightColor: '#DCC4C4',
 
};
export const Send_Icon = require ('../src/assets/images/send.png')
export const girl_Icon = require ('../src/assets/images/girl2.png')

export const fontFamilyStyles = {
  fontDomineBold: "dominebold",
  fontMetroPolisRegular: 'metropolisregular',
  fontPopinsRegular: 'Poppins-Regular',
  fontPopinsBold: 'Poppins-Bold',
};
export const width_screen = Dimensions.get('window').width;
